import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },

  header: {
    position: 'relative',
    height: 170,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#0D0D0D',
    padding: 24,
    paddingTop: 70,
  },
  form: {
    position: 'absolute',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    bottom: -25,
    zIndex: 999,
  },
  input: {
    flex: 1,
    height: 54,
    padding: 16,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#0D0D0D',
    backgroundColor: '#262626',
    fontSize: 16,
    color: '#FFF',
  },
  addButton: {
    width: 50,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#1E6F9F',
    borderRadius: 6,
  },
  buttonText: {
    width: 20,
    height: 20,
    fontSize: 14,
    color: '#FFF',
    borderWidth: 2,
    borderColor: '#FFF',
    borderRadius: 100,
    textAlign: 'center',
    fontWeight: 'bold',
  },
  listContainer: {
    flex: 1,
    padding: 24,
    paddingTop: 57,
    backgroundColor: '#1A1A1A',
  },
  listHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerTextContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderBottomColor: '',
  },
  headerText: {
    color: '#4EA8DE',
    fontWeight: 'bold',
    fontSize: 14,
  },
  headerText2: {
    color: '#8284FA',
    fontWeight: 'bold',
    fontSize: 14,
  },
  headerCount: {
    color: '#D9D9D9',
    fontWeight: 'bold',
    fontSize: 12,
    lineHeight: 17,
    backgroundColor: '#333333',
    width: 25,
    height: 19,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    borderRadius: 100,
  },
  list: {},
});
